<?php
declare(strict_types=1);

return [
    'utm-parametros-tabloide-digital' => [
        'titulo'    => 'UTM em Tabloides Digitais de Varejo: Rastreando Campanhas com Zero Erro | Toolbox Dev Design',
        'desc'      => 'Como a NuAto estrutura parâmetros UTM para gerenciar centenas de links rastreados em tabloides digitais de grandes redes de varejo — sem perda de dados no GA4.',
        'categoria' => 'Marketing Digital',
        'data'      => '2025-04-10',
        'ferramenta' => 'UTM em Massa',
        'ferramenta_url' => 'bulk-utm-generator',
    ],
    'teste-ab-criativo-varejo' => [
        'titulo'    => 'Teste A/B em Criativos de Varejo: O Que os Números Revelam na Prática | Toolbox Dev Design',
        'desc'      => 'Estudo de caso real: como aplicar teste A/B com significância estatística em campanhas de varejo de alto volume, interpretando Z-score e P-value para decisões de verba.',
        'categoria' => 'Performance',
        'data'      => '2025-04-17',
        'ferramenta' => 'Calculadora A/B',
        'ferramenta_url' => 'ab-test-calculator',
    ],
    'slug-ecommerce-alto-volume' => [
        'titulo'    => 'Slug Padronizado: A Fundação do SEO em E-commerce de Alto Volume | Toolbox Dev Design',
        'desc'      => 'Por que um slug inconsistente destrói o SEO de catálogos com milhares de SKUs — e o protocolo de padronização que usamos em grandes redes de varejo.',
        'categoria' => 'SEO',
        'data'      => '2025-04-24',
        'ferramenta' => 'Gerador de Slugs',
        'ferramenta_url' => 'slug-generator',
    ],
    'qr-code-pdv-metricas' => [
        'titulo'    => 'QR Code em PDV: Como Rastrear o Varejo Físico com Dados Digitais | Toolbox Dev Design',
        'desc'      => 'A metodologia da NuAto para integrar QR Codes em materiais de ponto de venda e medir o impacto do varejo físico em campanhas digitais — com dados reais.',
        'categoria' => 'Varejo Físico',
        'data'      => '2025-05-01',
        'ferramenta' => 'Gerador de QR Code',
        'ferramenta_url' => 'qr-generator',
    ],
    'json-feeds-produto-integracao' => [
        'titulo'    => 'JSON em Feeds de Produto: Integração Sem Erros em Redes de Varejo | Toolbox Dev Design',
        'desc'      => 'Como validar, formatar e depurar feeds JSON de produto para evitar inconsistências em integrações de e-commerce, marketplace e Google Shopping em grandes varejistas.',
        'categoria' => 'Desenvolvimento',
        'data'      => '2025-05-08',
        'ferramenta' => 'JSON Formatter',
        'ferramenta_url' => 'json-formatter',
    ],
    'bcrypt-portais-fornecedor' => [
        'titulo'    => 'BCrypt em Portais de Fornecedor: Segurança Real em Integrações B2B de Varejo | Toolbox Dev Design',
        'desc'      => 'Por que algoritmos fracos em portais de fornecedor criam risco jurídico e operacional — e como implementar BCrypt com custo adequado em integrações B2B de varejo.',
        'categoria' => 'Segurança',
        'data'      => '2025-05-15',
        'ferramenta' => 'Gerador de Hashes',
        'ferramenta_url' => 'hash-generator',
    ],
    'argon2id-apps-fidelidade' => [
        'titulo'    => 'Argon2id em Apps de Fidelidade: Por Que o Padrão de Segurança Importa no Varejo | Toolbox Dev Design',
        'desc'      => 'Análise técnica sobre por que Argon2id supera BCrypt e scrypt em ambientes com altos volumes de autenticação — como programas de fidelidade de redes de varejo.',
        'categoria' => 'Segurança',
        'data'      => '2025-05-22',
        'ferramenta' => 'Argon2id',
        'ferramenta_url' => 'argon2-generator',
    ],
    'contraste-wcag-encartes' => [
        'titulo'    => 'WCAG e Encartes Digitais: Quando Acessibilidade Vira Conversão no Varejo | Toolbox Dev Design',
        'desc'      => 'Como a análise de contraste WCAG melhora a leitura de preços e ofertas em tabloides digitais — e por que acessibilidade não é burocracia, é resultado de vendas.',
        'categoria' => 'Design & Acessibilidade',
        'data'      => '2025-05-29',
        'ferramenta' => 'Contraste WCAG',
        'ferramenta_url' => 'contrast-checker',
    ],
    'sha512-integridade-catalogo' => [
        'titulo'    => 'SHA-512 e a Integridade de Catálogo em Operações de Alto Volume de Varejo | Toolbox Dev Design',
        'desc'      => 'Como usar checksums SHA-512 para garantir que feeds de produto não foram corrompidos entre sistemas — protocolo real usado em integrações de redes de varejo.',
        'categoria' => 'Desenvolvimento',
        'data'      => '2025-06-05',
        'ferramenta' => 'SHA-512 / CRC32',
        'ferramenta_url' => 'sha512-crc32-generator',
    ],
    'base64-assets-campanha' => [
        'titulo'    => 'Base64 em Assets de Campanha: Velocidade Sem Abrir Mão da Privacidade | Toolbox Dev Design',
        'desc'      => 'Por que embutir assets críticos em Base64 resolve o problema de CORS e latência em hotsites de campanha de varejo — e quando não usar essa técnica.',
        'categoria' => 'Performance',
        'data'      => '2025-06-12',
        'ferramenta' => 'Base64 Encoder/Decoder',
        'ferramenta_url' => 'base64-encoder',
    ],
    'url-encoding-campanhas-varejo' => [
        'titulo'    => 'URL Encoding em Campanhas: O Erro Silencioso Que Corrompe UTMs e Perde Dados | Toolbox Dev Design',
        'desc'      => 'Como caracteres especiais em URLs de campanha corrompem parâmetros UTM silenciosamente — e o protocolo de validação que evita perda de dados no GA4.',
        'categoria' => 'Marketing Digital',
        'data'      => '2025-06-19',
        'ferramenta' => 'URL Encoder/Decoder',
        'ferramenta_url' => 'url-encoder-decoder',
    ],
    'meta-tags-landing-pages-varejo' => [
        'titulo'    => 'Meta Tags em Landing Pages de Promoção: SEO com Data de Validade no Varejo | Toolbox Dev Design',
        'desc'      => 'A estratégia de meta tags para páginas promocionais de curta duração em varejo — como ranquear rápido e evitar que Google indexe páginas expiradas.',
        'categoria' => 'SEO',
        'data'      => '2025-06-26',
        'ferramenta' => 'Gerador de Meta Tags SEO',
        'ferramenta_url' => 'meta-tags',
    ],
    'svg-materiais-pdv' => [
        'titulo'    => 'SVG Otimizado em Materiais de PDV: Performance Que Vai da Tela à Loja | Toolbox Dev Design',
        'desc'      => 'Por que o tamanho de SVG importa em hotsites de campanha e materiais impressos de PDV — e o processo de otimização que usamos para entregar assets em alta velocidade.',
        'categoria' => 'Design & Performance',
        'data'      => '2025-07-03',
        'ferramenta' => 'SVG Optimizer',
        'ferramenta_url' => 'svg-optimizer',
    ],
    'css-gradient-hotsite-blackfriday' => [
        'titulo'    => 'CSS Gradients em Hotsites de Black Friday: Do Briefing ao Ar em Horas | Toolbox Dev Design',
        'desc'      => 'Como aplicar gradientes CSS estratégicos para criar urgência visual em hotsites de Black Friday — com exemplos reais de campanhas para grandes redes de varejo.',
        'categoria' => 'Design',
        'data'      => '2025-07-10',
        'ferramenta' => 'Gerador de CSS Gradient',
        'ferramenta_url' => 'css-gradient',
    ],
    'paleta-cores-identidade-varejo' => [
        'titulo'    => 'Paleta de Cores por Segmento: Como o Varejo Controla Identidade Visual em Escala | Toolbox Dev Design',
        'desc'      => 'A metodologia de gestão de paletas de cor para redes com múltiplas lojas e canais — como garantir consistência de identidade visual em milhares de peças por mês.',
        'categoria' => 'Design',
        'data'      => '2025-07-17',
        'ferramenta' => 'Color Palette Generator',
        'ferramenta_url' => 'color-palette-generator',
    ],
    'uuid-rastreamento-promocoes' => [
        'titulo'    => 'UUID em Rastreamento de Brindes e Cashback: Sem Duplicidade, Sem Fraude | Toolbox Dev Design',
        'desc'      => 'Como UUIDs v4 garantem a unicidade de cupons, brindes e operações de cashback em programas de fidelidade de redes de varejo com milhões de transações.',
        'categoria' => 'Desenvolvimento',
        'data'      => '2025-07-24',
        'ferramenta' => 'Gerador de UUID',
        'ferramenta_url' => 'uuid-generator',
    ],
    'sql-relatorios-varejo' => [
        'titulo'    => 'SQL e Data-Driven Marketing: Relatórios Que Orientam Verba no Varejo de Alto Volume | Toolbox Dev Design',
        'desc'      => 'Queries SQL para análise de performance de campanha em varejo — como formatar, auditar e documentar código SQL para relatórios que orientam decisões de milhões.',
        'categoria' => 'Desenvolvimento',
        'data'      => '2025-07-31',
        'ferramenta' => 'Formatador de SQL',
        'ferramenta_url' => 'sql-formatter',
    ],
    'logistica-dados-black-friday' => [
        'titulo'    => 'Logística de Dados em Black Friday: O Que Acontece nos Bastidores de uma Grande Rede | Toolbox Dev Design',
        'desc'      => 'O fluxo de dados em uma Black Friday real — como grandes varejistas gerenciam milhares de SKUs, feeds, UTMs e integrações com zero tolerância a erro.',
        'categoria' => 'Varejo & Estratégia',
        'data'      => '2025-08-07',
        'ferramenta' => null,
        'ferramenta_url' => null,
    ],
    'prevencao-erros-encartes-digitais' => [
        'titulo'    => 'Prevenção de Erros em Encartes Digitais: O Protocolo de Validação da NuAto | Toolbox Dev Design',
        'desc'      => 'Como a NuAto estrutura um protocolo de validação em múltiplas camadas para garantir zero erros em encartes digitais de grandes redes — preços, slugs, UTMs e assets.',
        'categoria' => 'Varejo & Estratégia',
        'data'      => '2025-08-14',
        'ferramenta' => null,
        'ferramenta_url' => null,
    ],
    'arquitetura-tags-redes-farmacia' => [
        'titulo'    => 'Arquitetura de Tags para Redes de Farmácias: Rastreabilidade em Escala | Toolbox Dev Design',
        'desc'      => 'Como estruturar GTM, UTMs e eventos de Analytics para redes de farmácias com múltiplas filiais — garantindo rastreabilidade por loja, campanha e segmento.',
        'categoria' => 'Marketing Digital',
        'data'      => '2025-08-21',
        'ferramenta' => null,
        'ferramenta_url' => null,
    ],
];
